apiVersion: v1
kind: Service
metadata:
  name: {{ include "cabundle-operator.name" . }}-metrics-service
  labels:
    control-plane: controller-manager
  {{- include "cabundle-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    app.kubernetes.io/name: cabundle-operator
    control-plane: controller-manager
    {{- include "cabundle-operator.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.metricsService.ports | toYaml | nindent 2 }}
